### PR TITLE
JBTM-3814 H2 dependency should have runtime scope

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.redhat.com/browse/JBTM-3814

And there is some discussion of the issue on pr #170

### CODE REVIEW

**Review by jmfinelli — APPROVED** [review]

**Comment by mmusgrov** [comment]
@jmfinelli the tests passed but the job failed at the last step since the pod running the job does not have the linux hostname command:
```
narayana/scripts/hudson/jenkins.sh: line 103: hostname: command not found
+ '[' 127 = 0 ']'
+ fatal 'Store benchmark failed'
```
It only uses this command for the report, therefore I will rebase and merge but will then raise a scripts only PR to check for the existence of the `hostname` command.

**Comment by marcosgopen** [comment]
Thanks @mmusgrov for your PR!

**Comment by mmusgrov** [comment]
I came across a number of issues with the perf testing while fixing these bugs, I'll try and bring them together and raise a JBTM for them. I'm sure these issues have always been present and yet we haven't had a perf run failure for months, the last failure was probably last year so we should re-evaluate our test strategy.

**Comment by marcosgopen** [comment]
> I came across a number of issues with the perf testing while fixing these bugs, I'll try and bring them together and raise a JBTM for them. I'm sure these issues have always been present and yet we haven't had a perf run failure for months, the last failure was probably last year so we should re-evaluate our test strategy.

Thanks @mmusgrov for the follow up! I agree with you we should re-evaluate our test strategy, i.e. we should enable by default all tests/parameters in our CI job (see https://gitlab.cee.redhat.com/narayana/narayana-declaration/-/blob/main/jobs/narayana-performance.groovy#L73-76). Otherwise many steps are not tested regularly.

**Comment by mmusgrov** [comment]
The problem is that the results of the perf runs aren't useful so I'd definitely vote against enabling more testing until we know they provide added value.

**Comment by marcosgopen** [comment]
> The problem is that the results of the perf runs aren't useful so I'd definitely vote against enabling more testing until we know they provide added value.

Ok, I see. Thanks

**Pull request merged**
