### PR TITLE
Bump Atomikos dependencies

### PR DESCRIPTION
**Pull request by marcosgopen**
Upgrading Atomikos in order to have updated comparisons with Narayana.

### CODE REVIEW

**Comment by mmusgrov** [comment]
@marcosgopen I shan't approve until the job failure is fixed, but the changes do look reasonable.

**Comment by marcosgopen** [comment]
> Tests failed (https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/btny-pulls-performance/7/): git clone https://github.com/jbosstm/narayana.git failed

This job failed because 

> @marcosgopen I shan't approve until the job failure is fixed, but the changes do look reasonable.

The error you see is due to https://github.com/jbosstm/performance/pull/171
In fact the error is a "git clone error". I put the Hold label on this PR, I will remove it when https://github.com/jbosstm/performance/pull/171 will be merged.

**Review by mmusgrov — APPROVED** [review]

**Comment by mmusgrov** [comment]
@marcosgopen Approving because #171 has been merged.

**Comment by jmfinelli** [comment]
It looks like this PR is still failing :confused:

**Comment by mmusgrov** [comment]
> > Tests failed (https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/btny-pulls-performance/7/): git clone https://github.com/jbosstm/narayana.git failed
> 
> This job failed because
> 
> > @marcosgopen I shan't approve until the job failure is fixed, but the changes do look reasonable.
> 
> The error you see is due to #171 In fact the error is a "git clone error". I put the Hold label on this PR, I will remove it when #171 will be merged.

@marcosgopen #171 was merged so the error must be due to something else.

**Comment by mmusgrov** [comment]
@marcosgopen It looks like the issue is with running the JDBCStoreBenchmark performance test. That requires a database and as far as I know we don't configure one of those for the performance tests. But that benchmark has been around since 2015 so it should have always failed to run, I will investigate further.

**Comment by marcosgopen** [comment]
> @marcosgopen It looks like the issue is with running the JDBCStoreBenchmark performance test. That requires a database and as far as I know we don't configure one of those for the performance tests. But that benchmark has been around since 2015 so it should have always failed to run, I will investigate further.
> 
> [Update 1] I see that it uses H2 so it should work. I'll still investigate. BTW H2 is not renowned for its performance characteristics so this benchmark should be for tracking regressions as opposed to comparing it with our other stores.
> 
> [Update 2] The swallowed error is:
> 
> ```
> com.arjuna.ats.arjuna.exceptions.FatalError: com.arjuna.ats.internal.arjuna.objectstore.jdbc.accessors.DynamicDataSourceJDBCAccess@16f3aa4f : java.lang.ClassNotFoundException: org.h2.jdbcx.JdbcDataSource
> ```
> 
> while initialising the store (https://github.com/jbosstm/narayana/blob/main/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/objectstore/StoreManager.java#L136).
> 
> We need to find a way to report this error in a more transparent way.

Thanks Mike for your follow up and for having a look at the issue. I bumped into the issue with this PR, but I agree this issue has been around for a while. I put the 'Hold' label on this PR. When the issue is solved I will remove it (but I think the issue should be fix in a separated PR).

**Comment by mmusgrov** [comment]
@marcosgopen will you rebase this PR so that it can be retested.

**Comment by mmusgrov** [comment]
@marcosgopen the test failure is unrelated so this one can be merged now.

**Comment by marcosgopen** [comment]
Thanks @mmusgrov ! I will merge it then.

**Comment by marcosgopen** [comment]
BTW @mmusgrov and @jmfinelli I can see in the performance log that there is a failure due to the fact that the repo https://github.com/jbosstm-bot/artifacts does not have the 'main' branch. I will then create the 'main'  branch for that repository and then set it as default branch. I think I missed that repo when I originally moved the default branch from 'master' to 'main' because it is not under 'jbosstm' but under 'jbosstm-bot'.

**Comment by marcosgopen** [comment]
I wonder why https://github.com/**jbosstm-bot**/artifacts is used instead of https://github.com/**jbosstm**/artifacts , which exists too.

**Comment by marcosgopen** [comment]
Unfortunately I do not have permission for repo https://github.com/jbosstm-bot/artifacts . Do you @mmusgrov have permission for it?

**Comment by mmusgrov** [comment]
I didn't set up the jbosstm-bot repo, @jmfinelli do you know?

**Comment by jmfinelli** [comment]
> I didn't set up the jbosstm-bot repo, @jmfinelli do you know?

Nope, I don't know anything about it. Apparently, I don't have any permissions either.  Maybe @tomjenkinson has more info about that repo?

**Comment by jmfinelli** [comment]
> @marco I vote that we just remove the DO_NOT_PUBLISH option, we shouldn't be copying artifacts to the artifacts repo from pull jobs anyway.

Fair point

**Comment by marcosgopen** [comment]
> @marco I vote that we just remove the DO_NOT_PUBLISH option, we shouldn't be copying artifacts to the artifacts repo from pull jobs anyway.

I agree, I will remove that option from the performance pull job.

**Comment by marcosgopen** [comment]
> jbosstm-bot/artifacts now has a `main` branch and it is the default for that fork
> 
> (BTW the fork is used so that we have control over pushing the results to the main repo or something like that)

Thanks @tomjenkinson !

**Pull request merged**
