### PR TITLE
Fix issue with git command failing when Tag is used.

### PR DESCRIPTION
**Pull request by whitingjr**
fixes issue #175:Remove defining remote repository when reset command is used.

### CODE REVIEW

**Comment by jmfinelli** [comment]
TESTIT

**Review by mmusgrov — APPROVED** [review]

**Comment by mmusgrov** [comment]
Thanks Jeremy, I have triggered a test run ...

**Comment by marcosgopen** [comment]
Thanks @whitingjr for the PR. The error I see is not related to this PR. I will have a look at it.

**Comment by whitingjr** [comment]
Considering this further this PR may affect the execution when a branch (not a tag name) exists only in the local origin repository. Which is a problem for developers testing a local branch. Removing origin makes it ambiguous.

**Comment by mmusgrov** [comment]
> Removing origin makes it ambiguous.

So are you commenting on your own PR, do you still want to remove origin - from my point of view I'm still happy to approve it,

**Comment by mmusgrov** [comment]
> Thanks @whitingjr for the PR. The error I see is not related to this PR. I will have a look at it

There is a [post related to the error](https://fogbugz.atomikos.com/defaulteff5.html?community.6.3463.0) that suggests we upgrade atomikos, which we should do anyway since using old versions of other TMs is unfair.

**Comment by whitingjr** [comment]
@mmusgrov yes I see that error seen in the CI run is most likely due to the version.
Besides that I am inclined to abandon this PR.

**Comment by marcosgopen** [comment]
> > Thanks @whitingjr for the PR. The error I see is not related to this PR. I will have a look at it
> 
> There is a [post related to the error](https://fogbugz.atomikos.com/defaulteff5.html?community.6.3463.0) that suggests we upgrade atomikos, which we should do anyway since using old versions of other TMs is unfair.

Thanks Mike for sharing. BTW we are already using latest version of Atomikos which is 6.0.0

**Comment by marcosgopen** [comment]
> Considering this further this PR may affect the execution when a branch (not a tag name) exists only in the local origin repository. Which is a problem for developers testing a local branch. Removing origin makes it ambiguous.

I think I know what you mean. For that purpose you can use [this job](https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/narayana-performance) where you can set NARAYANA_REPO variable. So then origin will point to the NARAYANA_REPO remote you chose.

**Comment by marcosgopen** [comment]
I can see that the store benchmark failed. I will have a look at it but it is probably related to our environment. As soon as we move to the new performance Lab we will retest the performance job and double check it.

**Pull request closed without merging**
